include: package:solid_lints/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"

linter:
  rules:
    # تعطيل القواعد الصعبة مؤقتاً
    public_member_api_docs: false           # مش محتاج documentation دلوقتي
    lines_longer_than_80_chars: false      # اسمح بأسطر أطول
    avoid_print: false                      # اسمح بـ print
    sort_pub_dependencies: false           # متلزمنيش أرتب الـ dependencies
    
    # خلي القواعد المهمة شغالة
    use_build_context_synchronously: true  # دي مهمة للـ performance
    unawaited_futures: false               # دي ممكن تستنى
    deprecated_member_use: false           # دي مش حرجة دلوقتي