name: mishkat_almasabih
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.5.2
  
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  flutter_svg: ^2.2.0
  
  # HTTP and Networking
  dio: ^5.0.0
  retrofit: ^4.0.3
  json_annotation: 4.9.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  device_preview: ^1.2.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.2
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.2
  permission_handler: ^12.0.1
  font_awesome_flutter: ^10.9.1
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  fluttertoast: ^8.2.12
  solid_lints: ^0.3.1
  easy_notify: ^1.0.0
  flutter_background_service: ^5.1.0
  android_intent_plus: ^6.0.0
  transparent_image: ^2.0.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^17.2.4
  infinite_scroll_pagination: ^5.1.1
  custom_snackbar_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  retrofit_generator: ^9.7.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.1

flutter_launcher_icons:
  android: "ic_launcher.png"
  ios: true
  image_path: "assets/images/app_logo.png"   
  min_sdk_android: 21  

flutter:
  uses-material-design: true



  assets:
    - assets/images/
    - assets/images/first_onboardin.jpeg
    - assets/images/search_logo.jpg
    - assets/images/icons/search_icon.png
    - assets/images/book_covers/
    - assets/images/islamic_pattern.jpg
    - assets/images/moon-light-shine-through-window-into-islamic-mosque-interior.jpg

  fonts:
  - family: Amiri
    fonts:
      - asset: assets/fonts/Amiri-Regular.ttf
      - asset: assets/fonts/Amiri-Bold.ttf
        weight: 700
      - asset: assets/fonts/Amiri-Italic.ttf
        style: italic
      - asset: assets/fonts/Amiri-BoldItalic.ttf
        weight: 700
        style: italic

  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-Regular.ttf
      - asset: assets/fonts/Cairo-Light.ttf
        weight: 300
      - asset: assets/fonts/Cairo-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Cairo-Medium.ttf
        weight: 500
      - asset: assets/fonts/Cairo-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Cairo-Bold.ttf
        weight: 700
      - asset: assets/fonts/Cairo-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Cairo-Black.ttf
        weight: 900

  - family: YaModernPro
    fonts:
      - asset: assets/fonts/Ya-ModernPro-Bold.otf
        weight: 700
            


