name: mishkat_almasabih
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.5.0
  
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  flutter_svg: ^2.2.0
  
  # HTTP and Networking
  dio: ^5.0.0
  retrofit: ^4.0.3
  json_annotation: 4.9.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  retrofit_generator: ^9.7.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true



  assets:
    - assets/images/


  fonts:
      - family: FodaFree
        fonts:
          - asset: assets/fonts/Foda-Free-Font.ttf

      - family: YaModernPro
        fonts:
            - asset: assets/fonts/Ya-ModernPro-Bold.otf
            


