// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcbyX8tvaNJ0JgoqzgjFXnCClSNXbGzTc',
    appId: '1:752736333021:web:68a9b8704640e466c87f34',
    messagingSenderId: '752736333021',
    projectId: 'mishkat-50a1c',
    authDomain: 'mishkat-50a1c.firebaseapp.com',
    storageBucket: 'mishkat-50a1c.firebasestorage.app',
    measurementId: 'G-JCYSXN21QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZqCuZ0YzShjkmeyKqVO2XVIFer_SwR9o',
    appId: '1:752736333021:android:c3c0e16b66a2f0fbc87f34',
    messagingSenderId: '752736333021',
    projectId: 'mishkat-50a1c',
    storageBucket: 'mishkat-50a1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbSGU2V7X5SrnJ0h8ifnU5AgAC73w4SQo',
    appId: '1:752736333021:ios:b15496952c60ad38c87f34',
    messagingSenderId: '752736333021',
    projectId: 'mishkat-50a1c',
    storageBucket: 'mishkat-50a1c.firebasestorage.app',
    iosBundleId: 'com.example.mishkatAlmasabih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbSGU2V7X5SrnJ0h8ifnU5AgAC73w4SQo',
    appId: '1:752736333021:ios:b15496952c60ad38c87f34',
    messagingSenderId: '752736333021',
    projectId: 'mishkat-50a1c',
    storageBucket: 'mishkat-50a1c.firebasestorage.app',
    iosBundleId: 'com.example.mishkatAlmasabih',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcbyX8tvaNJ0JgoqzgjFXnCClSNXbGzTc',
    appId: '1:752736333021:web:d2c89581d3206c76c87f34',
    messagingSenderId: '752736333021',
    projectId: 'mishkat-50a1c',
    authDomain: 'mishkat-50a1c.firebaseapp.com',
    storageBucket: 'mishkat-50a1c.firebasestorage.app',
    measurementId: 'G-6EJYJJ46SF',
  );
}
